In [18]:
import tensorflow as tf

In [19]:
import os

In [21]:
print(os.getcwd())

C:\Users\tjdwo


In [27]:
a =2 
b=3

In [28]:
a+b

5

In [35]:
a= tf.constant([1,2,3])

In [40]:
b= tf.constant([4,5,6])

In [41]:
adding = tf.add(a,b)

In [42]:
sess = tf.Session()

In [43]:
print(sess.run(adding))

[5 7 9]


In [46]:
a= tf.constant(5, name='a')
b= tf.constant(3, name='b')
c= tf.multiply(a,b, name='c')
d= tf.add(a,b, name='d')
e= tf.add(c,d, name='e')

with tf.Session() as sess:
    sess.run(e)
    writer= tf.summary.FileWriter("./log", sess.graph)
    writer.close()


In [47]:
import os
print(os.getcwd())

C:\Users\tjdwo


In [50]:
input_data = [1,2,3,4,5]

x= tf.placeholder(dtype=tf.float32)
y= x*2

sess= tf.Session()
result= sess.run(y,feed_dict={x:input_data})
print(result)

[ 2.  4.  6.  8. 10.]


In [59]:
input_data = [1,2,3,4,5]

x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2], dtype=tf.float32)
y=W*x

sess= tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

result= sess.run(y,feed_dict={x:input_data})

print(result)

[ 2.  4.  6.  8. 10.]


In [61]:
x= tf.constant([[1,2,3,]], dtype=tf.float32)
w= tf.constant([[2],[2],[2]], dtype=tf.float32)

y= tf.matmul(x,w)
z= tf.multiply(x,w)

sess= tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

result_y = sess.run(y)
result_z = sess.run(z)

print(x.get_shape())
print(w.get_shape())
print()

print(y.get_shape())
print(z.get_shape())
print()

print(result_y)
print(result_z)

        

(1, 3)
(3, 1)

(1, 1)
(3, 3)

[[12.]]
[[2. 4. 6.]
 [2. 4. 6.]
 [2. 4. 6.]]


In [63]:
x= tf.placeholder(tf.float32, [None, 784])

W= tf.Variable(tf.zeros([784, 10]))
b= tf.Variable(tf.zeros([10]))

y= tf.nn.softmax(tf.matmul(x,W) +b)

In [64]:
print(y)

Tensor("Softmax:0", shape=(?, 10), dtype=float32)


In [22]:
import pprint as pp
import numpy as np
t= np.array([0.,1.,2.,3.,4.,5.,6.])
pp.pprint(t)

array([0., 1., 2., 3., 4., 5., 6.])


In [24]:
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [25]:
print(t.ndim)
print(t.shape)

1
(7,)


In [26]:
print(t[0], t[1], t[-1])

0.0 1.0 6.0


In [28]:
print(t[2:5]), t[4:-1]

[2. 3. 4.]


(None, array([4., 5.]))

In [29]:
print(t[:2], t[3:])

[0. 1.] [3. 4. 5. 6.]


In [57]:
t= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
pp.pprint(t)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


In [59]:
print(t.shape) # shape
print(t.ndim) # rank

(3, 3)
2


In [80]:
sess=tf.Session()
t = tf.constant([1,2,3,4])
tt=tf.shape(t).eval(session=sess)
tt

TypeError: eval() takes no keyword arguments

In [62]:
t= tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
print(t)
print(t.shape)

tt=tf.shape(t).eval(session=sess)
tt


Tensor("Const_20:0", shape=(1, 2, 3, 4), dtype=int32)
(1, 2, 3, 4)


array([1, 2, 3, 4])

In [74]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[1],[2]])
print(matrix1.shape)
print(matrix2.shape)

tf.matmul(matrix1, matrix2).eval(session=sess)

(2, 2)
(2, 1)


array([[ 5],
       [11]])

In [84]:

tf.reduce_mean([1,2], axis=0).eval(session=sess)


1

In [85]:
x= [[1,2],[3,4]]

In [89]:
tf.reduce_sum(x).eval(session=sess)

10

In [90]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([3, 7])

In [92]:
tf.argmax(x, axis==0).eval(session=sess)

NameError: name 'axis' is not defined

In [99]:
t = np.array([[[0,1,2],[3,4,5,]],[[7,8,9]],[10,11,12]])
t

array([list([[0, 1, 2], [3, 4, 5]]), list([[7, 8, 9]]),
       list([10, 11, 12])], dtype=object)

In [101]:
tf.squeeze([[0],[1],[2]]).eval(session=sess) ##차원줄임

array([0, 1, 2])

In [102]:
tf.expand_dims([0,1,2],1).eval(session=sess) ##차원늘임

array([[0],
       [1],
       [2]])

In [109]:
tf.one_hot([[0], [1], [2],[0]], depth=3).eval(session=sess)) 

SyntaxError: invalid syntax (<ipython-input-109-2ae61ee76e19>, line 1)

In [108]:
tf.cast([1.8,2.2,3.3,4.9], tf.int32).eval(session=sess)

array([1, 2, 3, 4])

In [110]:
tf.cast([True, False, 1==1, 0==1], tf.int32).eval(session=sess)

array([1, 0, 1, 0])