In [1]:
import os

In [2]:
import graphlab

In [3]:
sf=graphlab.SFrame('home_data.csv')

This non-commercial license of GraphLab Create for academic use is assigned to tjdwoocn@mju.ac.kr and will expire on March 05, 2019.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\tjdwo\AppData\Local\Temp\graphlab_server_1523255469.log.0


Finished parsing file C:\Users\tjdwo\home_data.csv

Parsing completed. Parsed 100 lines in 0.146944 secs.

------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[long,str,long,long,float,long,long,float,long,long,long,long,long,long,long,long,long,float,float,long,long]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------


Finished parsing file C:\Users\tjdwo\home_data.csv

Parsing completed. Parsed 21613 lines in 0.133584 secs.

In [4]:
sf

Columns:
	id	int
	date	str
	price	int
	bedrooms	int
	bathrooms	float
	sqft_living	int
	sqft_lot	int
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	int
	sqft_above	int
	sqft_basement	int
	yr_built	int
	yr_renovated	int
	zipcode	int
	lat	float
	long	float
	sqft_living15	int
	sqft_lot15	int

Rows: 21613

Data:
+------------+-----------------+---------+----------+-----------+-------------+
|     id     |       date      |  price  | bedrooms | bathrooms | sqft_living |
+------------+-----------------+---------+----------+-----------+-------------+
| 7129300520 | 20141013T000000 |  221900 |    3     |    1.0    |     1180    |
| 6414100192 | 20141209T000000 |  538000 |    3     |    2.25   |     2570    |
| 5631500400 | 20150225T000000 |  180000 |    2     |    1.0    |     770     |
| 2487200875 | 20141209T000000 |  604000 |    4     |    3.0    |     1960    |
| 1954400510 | 20150218T000000 |  510000 |    3     |    2.0    |     1680    |
| 7237550310 | 20140512T000000 | 1225000 |    4     |    4.5    |     5420    |
| 1321400060 | 20140627T000000 |  257500 |    3     |    2.25   |     1715    |
| 2008000270 | 20150115T000000 |  291850 |    3     |    1.5    |     1060    |
| 2414600126 | 20150415T000000 |  229500 |    3     |    1.0    |     1780    |
| 3793500160 | 20150312T000000 |  323000 |    3     |    2.5    |     1890    |
+------------+-----------------+---------+----------+-----------+-------------+
+----------+--------+------------+------+-----------+-------+------------+---------------+
| sqft_lot | floors | waterfront | view | condition | grade | sqft_above | sqft_basement |
+----------+--------+------------+------+-----------+-------+------------+---------------+
|   5650   |  1.0   |     0      |  0   |     3     |   7   |    1180    |       0       |
|   7242   |  2.0   |     0      |  0   |     3     |   7   |    2170    |      400      |
|  10000   |  1.0   |     0      |  0   |     3     |   6   |    770     |       0       |
|   5000   |  1.0   |     0      |  0   |     5     |   7   |    1050    |      910      |
|   8080   |  1.0   |     0      |  0   |     3     |   8   |    1680    |       0       |
|  101930  |  1.0   |     0      |  0   |     3     |   11  |    3890    |      1530     |
|   6819   |  2.0   |     0      |  0   |     3     |   7   |    1715    |       0       |
|   9711   |  1.0   |     0      |  0   |     3     |   7   |    1060    |       0       |
|   7470   |  1.0   |     0      |  0   |     3     |   7   |    1050    |      730      |
|   6560   |  2.0   |     0      |  0   |     3     |   7   |    1890    |       0       |
+----------+--------+------------+------+-----------+-------+------------+---------------+
+----------+--------------+---------+---------+----------+---------------+-----+
| yr_built | yr_renovated | zipcode |   lat   |   long   | sqft_living15 | ... |
+----------+--------------+---------+---------+----------+---------------+-----+
|   1955   |      0       |  98178  | 47.5112 | -122.257 |      1340     | ... |
|   1951   |     1991     |  98125  |  47.721 | -122.319 |      1690     | ... |
|   1933   |      0       |  98028  | 47.7379 | -122.233 |      2720     | ... |
|   1965   |      0       |  98136  | 47.5208 | -122.393 |      1360     | ... |
|   1987   |      0       |  98074  | 47.6168 | -122.045 |      1800     | ... |
|   2001   |      0       |  98053  | 47.6561 | -122.005 |      4760     | ... |
|   1995   |      0       |  98003  | 47.3097 | -122.327 |      2238     | ... |
|   1963   |      0       |  98198  | 47.4095 | -122.315 |      1650     | ... |
|   1960   |      0       |  98146  | 47.5123 | -122.337 |      1780     | ... |
|   2003   |      0       |  98038  | 47.3684 | -122.031 |      2390     | ... |
+----------+--------------+---------+---------+----------+---------------+-----+
[21613 rows x 21 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and col

In [5]:
sf['price'].mean()

540088.1419053345

In [6]:
sf.show(view='Categorical')

Canvas is accessible via web browser at the URL: http://localhost:8368/index.html
Opening Canvas in default web browser.


In [8]:
from graphlab.aggregate import*
a=sf.groupby('zipcode',{'mean price': MEAN('price')})
a

Columns:
	zipcode	int
	mean price	float

Rows: 70

Data:
+---------+---------------+
| zipcode |   mean price  |
+---------+---------------+
|  98118  | 417637.433071 |
|  98059  | 493552.521368 |
|  98109  | 879623.623853 |
|  98177  | 676185.392157 |
|  98058  | 353608.635165 |
|  98003  | 294111.278571 |
|  98133  | 386997.396761 |
|  98144  | 594547.641399 |
|  98024  | 580526.790123 |
|  98002  | 234284.035176 |
+---------+---------------+
[70 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [342]:
if sf['price'][1] >= a['mean price'][1]:
    print 'high'
else:
    print 'low'

high


In [363]:
if sf['zipcode'][1]== a['zipcode'][1]:
    

no


In [18]:
from graphlab.aggregate import*
a=sf.groupby('zipcode',{'mean price': MEAN('price')})
print a
print 
print 'zipcode별 평균 가격 중 최고가는=', a['mean price'].max()
print 'zipcode별 평균 가격 중 최저가는=', a['mean price'].min()

+---------+---------------+
| zipcode |   mean price  |
+---------+---------------+
|  98118  | 417637.433071 |
|  98059  | 493552.521368 |
|  98109  | 879623.623853 |
|  98177  | 676185.392157 |
|  98058  | 353608.635165 |
|  98003  | 294111.278571 |
|  98133  | 386997.396761 |
|  98144  | 594547.641399 |
|  98024  | 580526.790123 |
|  98002  | 234284.035176 |
+---------+---------------+
[70 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

zipcode별 평균 가격 중 최고가는= 2160606.6
zipcode별 평균 가격 중 최저가는= 234284.035176


In [19]:
a['zipcode', 'mean price'].sort('mean price', ascending=True)

Columns:
	zipcode	int
	mean price	float

Rows: 70

Data:
+---------+---------------+
| zipcode |   mean price  |
+---------+---------------+
|  98002  | 234284.035176 |
|  98168  | 240328.371747 |
|  98032  |   251296.24   |
|  98001  | 280804.690608 |
|  98148  | 284908.596491 |
|  98023  | 286732.791583 |
|  98188  | 289078.345588 |
|  98003  | 294111.278571 |
|  98030  | 296187.980469 |
|  98031  | 300539.890511 |
+---------+---------------+
[70 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [9]:
max(a)

{'mean price': 2160606.5999999996, 'zipcode': 98039L}

In [10]:
min(a)

{'mean price': 234284.03517587943, 'zipcode': 98002L}

In [20]:
a['zipcode', 'mean price'].sort('mean price', ascending=False)

Columns:
	zipcode	int
	mean price	float

Rows: 70

Data:
+---------+---------------+
| zipcode |   mean price  |
+---------+---------------+
|  98039  |   2160606.6   |
|  98004  | 1355927.09779 |
|  98040  | 1194230.00355 |
|  98112  | 1095499.36803 |
|  98102  | 901258.238095 |
|  98109  | 879623.623853 |
|  98105  | 862825.231441 |
|  98006  | 859684.763052 |
|  98119  |  849448.01087 |
|  98005  | 810164.880952 |
+---------+---------------+
[70 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [405]:
join_table=sf.join(a, on='zipcode', how='inner')
join_table

Columns:
	id	int
	date	str
	price	int
	bedrooms	int
	bathrooms	float
	sqft_living	int
	sqft_lot	int
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	int
	sqft_above	int
	sqft_basement	int
	yr_built	int
	yr_renovated	int
	zipcode	int
	lat	float
	long	float
	sqft_living15	int
	sqft_lot15	int
	high_low	float
	mean price	float

Rows: 21613

Data:
+------------+-----------------+---------+----------+-----------+-------------+
|     id     |       date      |  price  | bedrooms | bathrooms | sqft_living |
+------------+-----------------+---------+----------+-----------+-------------+
| 7129300520 | 20141013T000000 |  221900 |    3     |    1.0    |     1180    |
| 6414100192 | 20141209T000000 |  538000 |    3     |    2.25   |     2570    |
| 5631500400 | 20150225T000000 |  180000 |    2     |    1.0    |     770     |
| 2487200875 | 20141209T000000 |  604000 |    4     |    3.0    |     1960    |
| 1954400510 | 20150218T000000 |  510000 |    3     |    2.0    |     1680    |
| 7237550310 | 20140512T000000 | 1225000 |    4     |    4.5    |     5420    |
| 1321400060 | 20140627T000000 |  257500 |    3     |    2.25   |     1715    |
| 2008000270 | 20150115T000000 |  291850 |    3     |    1.5    |     1060    |
| 2414600126 | 20150415T000000 |  229500 |    3     |    1.0    |     1780    |
| 3793500160 | 20150312T000000 |  323000 |    3     |    2.5    |     1890    |
+------------+-----------------+---------+----------+-----------+-------------+
+----------+--------+------------+------+-----------+-------+------------+---------------+
| sqft_lot | floors | waterfront | view | condition | grade | sqft_above | sqft_basement |
+----------+--------+------------+------+-----------+-------+------------+---------------+
|   5650   |  1.0   |     0      |  0   |     3     |   7   |    1180    |       0       |
|   7242   |  2.0   |     0      |  0   |     3     |   7   |    2170    |      400      |
|  10000   |  1.0   |     0      |  0   |     3     |   6   |    770     |       0       |
|   5000   |  1.0   |     0      |  0   |     5     |   7   |    1050    |      910      |
|   8080   |  1.0   |     0      |  0   |     3     |   8   |    1680    |       0       |
|  101930  |  1.0   |     0      |  0   |     3     |   11  |    3890    |      1530     |
|   6819   |  2.0   |     0      |  0   |     3     |   7   |    1715    |       0       |
|   9711   |  1.0   |     0      |  0   |     3     |   7   |    1060    |       0       |
|   7470   |  1.0   |     0      |  0   |     3     |   7   |    1050    |      730      |
|   6560   |  2.0   |     0      |  0   |     3     |   7   |    1890    |       0       |
+----------+--------+------------+------+-----------+-------+------------+---------------+
+----------+--------------+---------+---------+----------+---------------+-----+
| yr_built | yr_renovated | zipcode |   lat   |   long   | sqft_living15 | ... |
+----------+--------------+---------+---------+----------+---------------+-----+
|   1955   |      0       |  98178  | 47.5112 | -122.257 |      1340     | ... |
|   1951   |     1991     |  98125  |  47.721 | -122.319 |      1690     | ... |
|   1933   |      0       |  98028  | 47.7379 | -122.233 |      2720     | ... |
|   1965   |      0       |  98136  | 47.5208 | -122.393 |      1360     | ... |
|   1987   |      0       |  98074  | 47.6168 | -122.045 |      1800     | ... |
|   2001   |      0       |  98053  | 47.6561 | -122.005 |      4760     | ... |
|   1995   |      0       |  98003  | 47.3097 | -122.327 |      2238     | ... |
|   1963   |      0       |  98198  | 47.4095 | -122.315 |      1650     | ... |
|   1960   |      0       |  98146  | 47.5123 | -122.337 |      1780     | ... |
|   2003   |      0       |  98038  | 47.3684 | -122.031 |      2390     | ... |
+----------+--------------+---------+---------+----------+---------------+-----+
[21613 rows x 23 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_col

In [406]:
join_table['mean price']

dtype: float
Rows: 21613
[310612.7557251908, 469455.7707317074, 462480.035335689, 551688.673003802, 685605.7755102044, 678163.0592592597, 294111.2785714283, 302878.88214285707, 359483.23958333343, 366867.6, 617105.0851063826, 619900.5506003437, 462480.035335689, 685605.7755102044, 579053.4172932331, 424706.3559322034, 424788.74736842094, 584919.2109634556, 234284.0351758795, 294111.2785714283, 386997.39676113316, 1194230.003546098, 334921.0626780626, 296187.9804687498, 296187.9804687498, 234284.0351758795, 849448.010869565, 1095499.3680297395, 619900.5506003437, 645231.4529616723, 616990.5873786411, 386997.39676113316, 576795.007233273, 576795.007233273, 353608.635164835, 619900.5506003437, 645231.4529616723, 579053.4172932331, 280804.6906077349, 420890.54926108377, 685605.7755102044, 464231.83858267695, 678163.0592592597, 849448.010869565, 353608.635164835, 424788.74736842094, 286732.7915831665, 617105.0851063826, 619900.5506003437, 487479.6271186439, 284908.596491228, 420890.54926108

In [435]:
def value(join_table):
    if join_table['price']>= join_table['mean price']:
        return 'high'
    else:
        return 'low'


In [440]:
join_table['high_low']=join_table.apply(value)
join_table['high_low'].head(5)

dtype: str
Rows: 5
['low', 'high', 'low', 'high', 'low']

In [445]:
join_table['zipcode','price','mean price','high_low'].head(5)

Columns:
	zipcode	int
	price	int
	mean price	float
	high_low	str

Rows: 5

Data:
+---------+--------+---------------+----------+
| zipcode | price  |   mean price  | high_low |
+---------+--------+---------------+----------+
|  98178  | 221900 | 310612.755725 |   low    |
|  98125  | 538000 | 469455.770732 |   high   |
|  98028  | 180000 | 462480.035336 |   low    |
|  98136  | 604000 | 551688.673004 |   high   |
|  98074  | 510000 |  685605.77551 |   low    |
+---------+--------+---------------+----------+
[5 rows x 4 columns]

In [3]:
import numpy as np
np.random.seed(1)
A= np.random.random((10,15))
B= np.random.random((10,15))

In [4]:
A

array([[  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
          3.02332573e-01,   1.46755891e-01,   9.23385948e-02,
          1.86260211e-01,   3.45560727e-01,   3.96767474e-01,
          5.38816734e-01,   4.19194514e-01,   6.85219500e-01,
          2.04452250e-01,   8.78117436e-01,   2.73875932e-02],
       [  6.70467510e-01,   4.17304802e-01,   5.58689828e-01,
          1.40386939e-01,   1.98101489e-01,   8.00744569e-01,
          9.68261576e-01,   3.13424178e-01,   6.92322616e-01,
          8.76389152e-01,   8.94606664e-01,   8.50442114e-02,
          3.90547832e-02,   1.69830420e-01,   8.78142503e-01],
       [  9.83468338e-02,   4.21107625e-01,   9.57889530e-01,
          5.33165285e-01,   6.91877114e-01,   3.15515631e-01,
          6.86500928e-01,   8.34625672e-01,   1.82882773e-02,
          7.50144315e-01,   9.88861089e-01,   7.48165654e-01,
          2.80443992e-01,   7.89279328e-01,   1.03226007e-01],
       [  4.47893526e-01,   9.08595503e-01,   2.93614148e-01,
     

In [5]:
A[1:2,2:3]

array([[ 0.55868983]])

In [6]:
A[1,2]

0.55868982844575166

In [8]:
c=A.mean(axis=1)
print c
c[4]

[ 0.35737762  0.51351808  0.54782915  0.38654201  0.48705829  0.62454269
  0.52268167  0.56865919  0.43022285  0.37170517]


0.48705829032763209

In [9]:
A.sum()

72.152050947270865

In [10]:
B.sum()

80.390745946150261

In [11]:
A.sum()-B.sum()

-8.2386949988793958

In [268]:
A*B

array([[  3.00148584e-02,   6.96752832e-01,   6.49763866e-05,
          6.14621666e-02,   3.70302894e-02,   6.86838341e-02,
          3.64007365e-02,   2.00894814e-01,   3.84872381e-01,
          4.56285529e-01,   1.00542865e-01,   3.38340637e-01,
          1.26751341e-01,   7.27942582e-01,   4.29413893e-03],
       [  1.24547400e-02,   2.92205768e-02,   2.71716067e-01,
          8.51207369e-02,   1.12690317e-01,   2.54126226e-01,
          9.57239035e-01,   1.81706169e-01,   2.63180331e-01,
          4.82845043e-01,   6.66781148e-01,   5.69143836e-02,
          1.03463759e-02,   1.12656728e-02,   3.24986664e-01],
       [  6.19307230e-02,   8.85058782e-02,   7.21056664e-01,
          3.54749420e-02,   1.80106059e-01,   2.53912644e-01,
          1.32792814e-01,   5.33710467e-01,   9.59531613e-03,
          6.93739441e-01,   2.60363931e-01,   4.93498226e-02,
          2.06144833e-01,   6.09464157e-01,   9.37102052e-02],
       [  4.17424256e-01,   1.26763365e-02,   6.88120243e-02,
     

In [295]:
A[1,:]

array([ 0.67046751,  0.4173048 ,  0.55868983,  0.14038694,  0.19810149,
        0.80074457,  0.96826158,  0.31342418,  0.69232262,  0.87638915,
        0.89460666,  0.08504421,  0.03905478,  0.16983042,  0.8781425 ])

A=A.reshape((3,3))

In [293]:
A.dtype

dtype('float64')

In [294]:
A[1,:]

array([ 0.67046751,  0.4173048 ,  0.55868983,  0.14038694,  0.19810149,
        0.80074457,  0.96826158,  0.31342418,  0.69232262,  0.87638915,
        0.89460666,  0.08504421,  0.03905478,  0.16983042,  0.8781425 ])

In [25]:
import numpy as np

In [26]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [43]:
BA=A*B

In [58]:
BAT=BA.transpose()
BAT

array([[  3.00148584e-02,   1.24547400e-02,   6.19307230e-02,
          4.17424256e-01,   4.04093703e-02,   1.55450718e-01,
          3.61730716e-02,   5.16669419e-01,   7.98146785e-03,
          1.99169227e-01],
       [  6.96752832e-01,   2.92205768e-02,   8.85058782e-02,
          1.26763365e-02,   3.98844618e-01,   5.39823146e-01,
          8.47788238e-01,   9.09265028e-03,   8.31894644e-03,
          4.25921233e-01],
       [  6.49763866e-05,   2.71716067e-01,   7.21056664e-01,
          6.88120243e-02,   1.20794842e-01,   3.05627761e-01,
          2.59984973e-01,   5.83757404e-01,   1.76043531e-02,
          3.11126715e-01],
       [  6.14621666e-02,   8.51207369e-02,   3.54749420e-02,
          1.77493601e-01,   5.23230681e-02,   6.34236846e-01,
          1.06429590e-01,   1.97303773e-01,   1.05931640e-01,
          4.94367796e-01],
       [  3.70302894e-02,   1.12690317e-01,   1.80106059e-01,
          1.23399237e-01,   6.74767118e-03,   6.57312999e-01,
          3.21582918e-01

In [60]:
Bt= B.transpose()

In [61]:
BT=Bt.reshape((10,15))

In [55]:
A*BT

array([[  3.00148584e-02,   1.33808934e-02,   7.20238248e-05,
          2.81765513e-01,   5.79503223e-02,   8.68082039e-02,
          5.87175637e-02,   2.86416560e-01,   1.59294040e-01,
          4.60633317e-01,   4.05476931e-01,   4.79805383e-02,
          4.29705492e-02,   1.22511195e-02,   2.63814423e-02],
       [  3.90221598e-01,   3.72606746e-01,   3.21085472e-01,
          4.45565605e-02,   1.04541057e-01,   4.54903359e-01,
          4.70909283e-01,   2.35931791e-01,   1.62254172e-01,
          1.52452859e-01,   7.86208949e-01,   4.91434112e-02,
          2.45293798e-02,   1.05620827e-01,   7.04411742e-01],
       [  1.99932460e-02,   2.55329960e-01,   6.37345989e-02,
          3.28844808e-01,   8.74045033e-02,   2.66526922e-01,
          1.26323174e-01,   2.38349296e-01,   7.86848142e-03,
          4.29449007e-01,   2.49515111e-01,   4.25595108e-01,
          7.30038054e-02,   7.49038964e-01,   1.39436821e-02],
       [  4.05519358e-01,   7.15908959e-01,   1.72302572e-01,
     

In [90]:
At=A.transpose()
Bs=B.reshape(15,10)
BsAt=Bs*At
BsAt.sum(axis=0)

array([ 2.38948038,  5.8824034 ,  4.44143056,  2.51222864,  3.16872214,
        5.64933903,  2.28655408,  4.56633871,  4.13565462,  4.1509681 ])

In [92]:
BsAtsum=BsAt.sum(axis=0)
BsAtsum[1:2]

array([ 5.8824034])

In [75]:
A.sum(axis=1)

array([ 5.36066437,  7.70277124,  8.21743728,  5.79813014,  7.30587435,
        9.36814037,  7.84022502,  8.52988791,  6.45334276,  5.5755775 ])

In [78]:
A.transpose()

array([[  4.17022005e-01,   6.70467510e-01,   9.83468338e-02,
          4.47893526e-01,   1.02334429e-01,   1.65354197e-01,
          1.14745973e-01,   6.23360116e-01,   1.98801338e-02,
          2.32974274e-01],
       [  7.20324493e-01,   4.17304802e-01,   4.21107625e-01,
          9.08595503e-01,   4.14055988e-01,   9.27508580e-01,
          9.49489259e-01,   1.58212428e-02,   2.62109869e-02,
          8.07105196e-01],
       [  1.14374817e-04,   5.58689828e-01,   9.57889530e-01,
          2.93614148e-01,   6.94400158e-01,   3.47765860e-01,
          4.49912133e-01,   9.29437234e-01,   2.83064880e-02,
          3.87860644e-01],
       [  3.02332573e-01,   1.40386939e-01,   5.33165285e-01,
          2.87775339e-01,   4.14179270e-01,   7.50812103e-01,
          5.78389614e-01,   6.90896918e-01,   2.46211068e-01,
          8.63541855e-01],
       [  1.46755891e-01,   1.98101489e-01,   6.91877114e-01,
          1.30028572e-01,   4.99534589e-02,   7.25997985e-01,
          4.08136803e-01

In [77]:
A.reshape(15,10)

array([[  4.17022005e-01,   7.20324493e-01,   1.14374817e-04,
          3.02332573e-01,   1.46755891e-01,   9.23385948e-02,
          1.86260211e-01,   3.45560727e-01,   3.96767474e-01,
          5.38816734e-01],
       [  4.19194514e-01,   6.85219500e-01,   2.04452250e-01,
          8.78117436e-01,   2.73875932e-02,   6.70467510e-01,
          4.17304802e-01,   5.58689828e-01,   1.40386939e-01,
          1.98101489e-01],
       [  8.00744569e-01,   9.68261576e-01,   3.13424178e-01,
          6.92322616e-01,   8.76389152e-01,   8.94606664e-01,
          8.50442114e-02,   3.90547832e-02,   1.69830420e-01,
          8.78142503e-01],
       [  9.83468338e-02,   4.21107625e-01,   9.57889530e-01,
          5.33165285e-01,   6.91877114e-01,   3.15515631e-01,
          6.86500928e-01,   8.34625672e-01,   1.82882773e-02,
          7.50144315e-01],
       [  9.88861089e-01,   7.48165654e-01,   2.80443992e-01,
          7.89279328e-01,   1.03226007e-01,   4.47893526e-01,
          9.08595503e-01

In [79]:
0.4*0.5

0.2

In [80]:
0.2*10

2.0

In [97]:
At=A.transpose()
BAT=np.dot(B, At)
BATsum=BAT.sum(axis=0)
BATsum[1:2]

array([ 40.96473483])

In [102]:
At=A.transpose()
BAT=np.dot(B, At)
BATD=np.diag(BAT)

In [103]:
BATD.sum()

39.712370706394459

In [106]:
Bt=B.transpose()
ABT=np.dot(A,Bt)
ABT

array([[ 3.27033398,  2.08006645,  2.51897243,  3.26561261,  2.67956706,
         2.78341814,  3.54022703,  3.19884071,  2.8500405 ,  2.94675005],
       [ 3.78784017,  3.72059349,  4.39542691,  4.88067942,  2.74825142,
         4.7802464 ,  3.83243841,  5.0009696 ,  3.96540212,  3.8528869 ],
       [ 4.19954571,  4.29954293,  3.9298579 ,  4.97056627,  2.8977388 ,
         5.01199174,  4.55390303,  4.89215662,  4.95454157,  4.48748838],
       [ 3.09866541,  2.39583805,  2.87325934,  3.39414319,  2.54665202,
         3.3828957 ,  3.65986503,  3.58474255,  2.62167354,  3.24241244],
       [ 4.24239617,  3.45818244,  3.97548484,  4.46348142,  3.19632875,
         4.21754947,  3.89297949,  4.35182001,  3.66820454,  3.85080915],
       [ 4.89681504,  4.20290088,  4.59418508,  6.01372392,  3.85449189,
         5.77678352,  4.96993595,  5.290875  ,  5.13601857,  4.55793752],
       [ 3.94106204,  3.70312789,  3.932457  ,  4.59529875,  2.81219366,
         4.89620741,  4.32152103,  4.61804258